### ISSUE TITLE
Should we rename the lib?

### ISSUE THREAD

**Issue by g-andrade** [miniclip/erl_cbor#3]
Even though we can publish `erl-cbor` under an `mc_cbor` or suchlike package name, it will still collide with [an existing Elixir library](https://hex.pm/packages/cbor), which may hinder adoption of a particular dependent of this library yet to be publicly released.

Since we now have total control over this library and have yet to publish its first release to Hex.pm, simply renaming it could make our lives easier.

**Comment by paulo-ferraz-oliveira** [comment]
I'm Okay with calling it `erl_cbor`, if naming collisions worries you. In any case we've used this strategy (`mc_` prefix) in the past, for stuff not originally created by us...

**Comment by g-andrade** [comment]
> In any case we've used this strategy (mc_ prefix) in the past, for stuff not originally created by us...

Sure, for the package name - the library name is a distinct matter, IMO.

**Comment by paulo-ferraz-oliveira** [comment]
I'm Okay as-is, in that case. It's unlikely you're going to use two lib.s in the same scope with the same name. Might happen, but unlikely. Also, I was making the comment for both the lib. name and the package name, and in that case we should also rename the Git repo., since it's kinda odd that 2 of these don't match.
